require 'win32ole'
require 'open-uri'
require 'singleton'

require 'rubygems'
require 'trollop'

require 'lib/formatting_dsl/module'
require 'lib/formatting_dsl/format_extractor'
require 'lib/formatting_dsl/format_handler'
require 'lib/formatting_dsl/toggle_format_handler'
require 'lib/formatting_dsl/formatting_handler'

require 'lib/rgb'
require 'lib/format'
require 'lib/formatting'
require 'lib/formattings'

require 'lib/parser/base_parser'
require 'lib/parser/code_parser'
require 'lib/parser/xml_parser'
require 'lib/parser/command_node'
require 'lib/parser/text_node'
require 'lib/parser/tag_matcher'
require 'lib/parser/tag_match'

require 'lib/shape_formatter'
require 'lib/formattable_text'

require 'lib/power_point'
require 'lib/power_point/application'
require 'lib/power_point/presentation'
require 'lib/power_point/slide'
require 'lib/power_point/shape'
require 'lib/power_point/text_range'